# Run command: docker-compose -f docker-compose.dev.yml up -d
# Stop command: docker-compose -f docker-compose.dev.yml stop
# Destroy command: docker-compose -f docker-compose.dev.yml down -v
version: '3.8'
services:
  mysql-musicplayer-docker:
    image: mysql:8.0
    container_name: mysql-musicplayer-docker
    ports:
      - "3306:3306"
    volumes:
      - mysql-docker-data:/var/lib/mysql
      - mysql-docker-config-deamond:/etc/mysql/conf.d
    environment:
      MYSQL_USER: lam
      MYSQL_PASSWORD: 870124zxc
      MYSQL_ROOT_PASSWORD: 870124zxc
      MYSQL_DATABASE: dbmusic
    restart: unless-stopped
volumes:
  mysql-docker-data:
  mysql-docker-config-deamond:
